### ISSUE TITLE
devcenter pull returns documents with mixed newline encoding

### ISSUE THREAD

**Issue by raul** [heroku/devcenter-cli#12]
@fdr reports: "It seems to use both CRLF (for the bulk of the text, probably
converted by the browser since that kind of newline is
Internet-standard) and just LF for the header emitted by 'devcenter
pull'.  The resultant mix of line terminators causes sufficiently
pedantic editors annoyingly render the CR character, as it does not
decode cleanly with either format applied uniformly".

**Comment by fdr** [comment]
Blast from the past!
