### ISSUE TITLE
Support new look dev center

### ISSUE THREAD

**Issue by robanderton** [heroku/devcenter-cli#22]
Hi,

Now the Dev Center has had a makeover could the CLI get an update so that local previews also get the new look?

Thanks,
Rob

**Comment by raul** [comment]
We have a few things to nail down first but we should definitely make this happen, thank you @robanderton !

**Comment by hannesfostie** [comment]
@robanderton You should now be able to preview articles using the new look in version 1.1.8 - let us know if you spot any inconsistencies!

Enjoy the holiday season :-)
