### ISSUE TITLE
Some dependencies trigger warnings (in ruby 2.5.0)

### ISSUE THREAD

**Issue by mikehale** [heroku/devcenter-cli#26]
Steps to fix:

```
bundle update # grabs latest deps
# update lib/devcenter/version.rb to next version
rake release
```

**Comment by raul** [comment]
Hey Mike, thank you for reporting this! We'd like to know how to prioritize the issue, are the warnings blocking any workflow?

**Comment by mikehale** [comment]
No, everything is still functional, just an annoying wall of warning text :)

**Comment by raul** [comment]
Gotcha, in that case we'll keep this present and jump into it at some point, but won't be a high priority right now: we'll want to double-check that things keep working after the update in other Ruby versions so this might not be a quick fix. Thank you @mikehale ! ❤️
